package de.bananajoh.sv650overlay;


public class DataInfo {
    public static final DataInfoEntry[] ENTRIES = {
        new DataInfoEntry("0", "", -1),
        new DataInfoEntry("1", "", -1),
        new DataInfoEntry("2", "", -1),
        new DataInfoEntry("3", "", -1),
        new DataInfoEntry("4", "", -1),
        new DataInfoEntry("5", "", -1),
        new DataInfoEntry("6?", "", -1),
        new DataInfoEntry("7", "", -1),
        new DataInfoEntry("8", "", -1),
        new DataInfoEntry("9", "", -1),
        new DataInfoEntry("10", "", -1),
        new DataInfoEntry("11", "", -1),
        new DataInfoEntry("12", "", -1),
        new DataInfoEntry("13", "", -1),
        new DataInfoEntry("14", "", -1),
        new DataInfoEntry("15", "", -1),
        new DataInfoEntry("16", "", -1),
        new DataInfoEntry("RPM", "", 0),
        new DataInfoEntry("18", "", -1),
        new DataInfoEntry("TPS", " %", 1),
        new DataInfoEntry("IAP1", "", 6),
        new DataInfoEntry("ECT", " °C", 3),
        new DataInfoEntry("IAT", " °C", 4),
        new DataInfoEntry("23", "", -1),
        new DataInfoEntry("BATT", " V", 2),
        new DataInfoEntry("HO2", "", 8),
        new DataInfoEntry("GPS", "", 5),
        new DataInfoEntry("IAP2", "", 7),
        new DataInfoEntry("IDLE", "", 11),
        new DataInfoEntry("ISCV", "", 14),
        new DataInfoEntry("30", "", -1),
        new DataInfoEntry("FUEL1a", "", 9),
        new DataInfoEntry("FUEL1b", "", 12),
        new DataInfoEntry("FUEL2a", "", 10),
        new DataInfoEntry("FUEL2b", "", 13),
        new DataInfoEntry("35", "", -1),
        new DataInfoEntry("36", "", -1),
        new DataInfoEntry("37", "", -1),
        new DataInfoEntry("38", "", -1),
        new DataInfoEntry("39", "", -1),
        new DataInfoEntry("40", "", -1),
        new DataInfoEntry("IGN1", "", 15),
        new DataInfoEntry("IGN2", "", 16),
        new DataInfoEntry("43", "", -1),
        new DataInfoEntry("44", "", -1),
        new DataInfoEntry("45", "", -1),
        new DataInfoEntry("STV", "", 17),
        new DataInfoEntry("47", "", -1),
        new DataInfoEntry("48", "", -1),
        new DataInfoEntry("49", "", -1),
        new DataInfoEntry("50", "", -1),
        new DataInfoEntry("PAIR", "", 18),
        new DataInfoEntry("C/M/TO", "", 19),
        new DataInfoEntry("N", "", 20),
        new DataInfoEntry("54", "", -1),
        new DataInfoEntry("55", "", -1),
        new DataInfoEntry("SUM", "", -1)
    };
}
