package de.bananajoh.sv650overlay;


public class DataInfo {
    public static final DataInfoEntry[] ENTRIES = {
        new DataInfoEntry("6", "", false),
        new DataInfoEntry("7", "", false),
        new DataInfoEntry("8", "", false),
        new DataInfoEntry("9", "", false),
        new DataInfoEntry("10", "", false),
        new DataInfoEntry("11", "", false),
        new DataInfoEntry("12", "", false),
        new DataInfoEntry("13", "", false),
        new DataInfoEntry("14?", "", false),
        new DataInfoEntry("15", "", false),
        new DataInfoEntry("16", "", false),
        new DataInfoEntry("17", "", false),
        new DataInfoEntry("18", "", false),
        new DataInfoEntry("19", "", false),
        new DataInfoEntry("20", "", false),
        new DataInfoEntry("21", "", false),
        new DataInfoEntry("22", "", false),
        new DataInfoEntry("23", "", false),
        new DataInfoEntry("24", "", false),
        new DataInfoEntry("RPM", "", true),
        new DataInfoEntry("26", "", false),
        new DataInfoEntry("TPS", " %", true),
        new DataInfoEntry("IAP1", "", true),
        new DataInfoEntry("ECT", " °C", true),
        new DataInfoEntry("IAT", " °C", true),
        new DataInfoEntry("31", "", false),
        new DataInfoEntry("BATT", " V", true),
        new DataInfoEntry("HO2", "", true),
        new DataInfoEntry("GPS", "", true),
        new DataInfoEntry("IAP2", "", true),
        new DataInfoEntry("IDLE", "", true),
        new DataInfoEntry("ISCV", "", true),
        new DataInfoEntry("38", "", false),
        new DataInfoEntry("FUEL1a", "", true),
        new DataInfoEntry("FUEL1b", "", true),
        new DataInfoEntry("FUEL2a", "", true),
        new DataInfoEntry("FUEL2b", "", true),
        new DataInfoEntry("43", "", false),
        new DataInfoEntry("44", "", false),
        new DataInfoEntry("45", "", false),
        new DataInfoEntry("46", "", false),
        new DataInfoEntry("47", "", false),
        new DataInfoEntry("48", "", false),
        new DataInfoEntry("IGN1", "", true),
        new DataInfoEntry("IGN2", "", true),
        new DataInfoEntry("51", "", false),
        new DataInfoEntry("52", "", false),
        new DataInfoEntry("53", "", false),
        new DataInfoEntry("STV", "", true),
        new DataInfoEntry("55", "", false),
        new DataInfoEntry("56", "", false),
        new DataInfoEntry("57", "", false),
        new DataInfoEntry("58", "", false),
        new DataInfoEntry("PAIR", "", true),
        new DataInfoEntry("C/M/TO", "", true),
        new DataInfoEntry("N", "", true),
        new DataInfoEntry("62", "", false),
        new DataInfoEntry("63", "", false),
        new DataInfoEntry("SUM", "", false)
    };
}
